name: Website Template
description: A starting point for building static websites.
exclude: [README.md, Gemfile, Gemfile.lock, .bundle, vendor/bundle,
          gulpfile.js, node_modules, package.json]
